# .goreleaser.yml
# Build customization
project_name: mmock-jcd
builds:
  - main: cmd/mmock/main.go
    binary: mmock
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
     - -X main.VERSION={{.Version}}
archives:
  - id: mmock
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - dockerfile: Dockerfile
    skip_push: false
    goarch: amd64
    use: buildx
    image_templates:
      - "artifacts.cnco.tucows.systems/mse-mint-docker/mmock-jcd:{{.Tag}}-amd64"
    extra_files:
      - tls/server.crt
      - tls/server.key
    build_flag_templates:
      - "--platform=linux/amd64"
  - dockerfile: Dockerfile
    skip_push: false
    goarch: arm64
    use: buildx
    image_templates:
      - "artifacts.cnco.tucows.systems/mse-mint-docker/mmock-jcd:{{.Tag}}-arm64"
    extra_files:
      - tls/server.crt
      - tls/server.key
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "artifacts.cnco.tucows.systems/mse-mint-docker/mmock-jcd:latest"
    image_templates:
      - artifacts.cnco.tucows.systems/mse-mint-docker/mmock-jcd:{{ .Tag }}-amd64
      - artifacts.cnco.tucows.systems/mse-mint-docker/mmock-jcd:{{ .Tag }}-arm64
  - name_template: "jordimartin/mmock:{{.Tag}}"
    image_templates:
      - artifacts.cnco.tucows.systems/mse-mint-docker/mmock-jcd:{{ .Tag }}-amd64
      - artifacts.cnco.tucows.systems/mse-mint-docker/mmock-jcd:{{ .Tag }}-arm64
release:
  github:
    owner: jdietrich-tc 
    name: mmock-jcd
  draft: false
changelog:
  filters:
    exclude:
      - '^docs:'
      - typo
      - rollback
env_files:
  github_token: .github
